menu:
    Blog: /
    Archive: /archives/
    Linkedin: https://tw.linkedin.com/in/lance-cheng-33532b5
    GitHub: https://github.com/gralance
    Rss: /atom.xml

favicon: /favicon.png


# Comment
# e.g disqus: seansun
disqus: lance-1
duoshuo:

# Analytics
# google-analytics:
ga: UA-82107277-1

# Copyright Infomation
startyear: 2015
