menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/gralance
    Resume: "/resume/"
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: lance-1
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
